
name: Ghost PUBG Dylib Compile
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Absolute iOS PUBG Dylib Construction
        run: |
          xcrun -sdk iphoneos clang++ -dynamiclib -arch arm64 \
          -framework UIKit -framework Foundation -framework QuartzCore -framework CoreGraphics -framework CFNetwork \
          xerx_pubg_ios.mm -o XERX_PUBG_IOS.dylib
      - uses: actions/upload-artifact@v4
        with:
          name: xerx_pubg_payload
          path: XERX_PUBG_IOS.dylib
